### PR TITLE
More updates and adjustments

### PR DESCRIPTION
**Pull request by jescalan**
Fully replaces the previous version nextjs-scripts with the broken apart packages, which was only partially completed in my last cleanup PR!

### CODE REVIEW

**Review by BRKalow — APPROVED** [review]
🏆

**Review by kylemac — APPROVED** [review]
ran locally and lgtm! but bryce's was the more important review here!

**Review by mwickett — COMMENTED** [review]
Tried running this locally and got a missing `typescript` dev-dep error. Maybe just me? Adding it fixed the problem. 

CleanShot 2021-07-20 at 12 45 00@2x

**Comment by jescalan** [comment]
Great catch @mwickett - i wonder why kyle and i didnt get the same error 🤔

**Pull request merged**
